version: 1.0.{build}

cache:
  # cache local::lib
  - C:\msys64\mingw64\lib\perl5\site_perl -> appveyor.yml
  - C:\msys64\mingw64\bin\cpanm -> appveyor.yml
  - C:\msys64\mingw64\bin\dzil -> appveyor.yml
  - C:\msys64\home\%Username%\perl5 -> appveyor.yml
  - maint/cpanfile-git-log -> appveyor.yml

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  # running under CI
  - set CI_TESTING=1
  - set DEVOPS_BRANCH=master
  - cinst curl -y
  - 'cd %APPVEYOR_BUILD_FOLDER% & curl -fsS -o helper.pl https://raw.githubusercontent.com/project-renard/devops/%DEVOPS_BRANCH%/script/helper.pl & perl helper.pl install'
  - 'echo End intall at: & time /t'

build_script:
  - 'echo Nothing to build'

test_script:
  - 'cd %APPVEYOR_BUILD_FOLDER% & perl helper.pl test'
